name: focal_agent_coding_task
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Network services
  http: ^0.13.5
  connectivity_plus: ^5.0.2

  # State Management
  flutter_bloc: ^8.1.3

  # Dependency Injection
  injectable: ^2.3.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Mocks
  mockito: ^5.4.4

  # Code generation
  build_runner: ^2.4.7
  injectable_generator: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
